# Generated by Django 4.2.25 on 2025-10-13 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establishments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField()),
                ('purchase_time', models.TimeField(blank=True, null=True)),
                ('subtotal_ves', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_ves', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_ves', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bcv_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('binance_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('total_usd_bcv', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_usd_binance', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('tax_ves', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_type', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_base', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('card_last_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('tip_ves', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cashier', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('register_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='establishments.establishment')),
            ],
            options={
                'db_table': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='SpendingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='purchases.spendingcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spending_categories',
            },
        ),
        migrations.CreateModel(
            name='PurchaseSpendingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.spendingcategory')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
            ],
            options={
                'db_table': 'purchase_spending_categories',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_type', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discount_ves', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_ves', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal_ves', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price_usd_bcv', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unit_price_usd_binance', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('subtotal_usd_bcv', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('subtotal_usd_binance', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_per_unit_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('price_per_unit_usd_bcv', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_per_unit_usd_binance', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='products.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase')),
            ],
            options={
                'db_table': 'purchase_items',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='spending_categories',
            field=models.ManyToManyField(related_name='purchases', through='purchases.PurchaseSpendingCategory', to='purchases.spendingcategory'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='spendingcategory',
            index=models.Index(fields=['user'], name='idx_spending_categories_user'),
        ),
        migrations.AlterUniqueTogether(
            name='spendingcategory',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='purchasespendingcategory',
            index=models.Index(fields=['purchase'], name='idx_purch_spend_purchase'),
        ),
        migrations.AddIndex(
            model_name='purchasespendingcategory',
            index=models.Index(fields=['category'], name='idx_purch_spend_category'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasespendingcategory',
            unique_together={('purchase', 'category')},
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase'], name='idx_purch_items_purchase'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['product'], name='idx_purch_items_product'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['product', 'created_at'], name='idx_purch_item_prod_date'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user'], name='idx_purchases_user'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_date'], name='idx_purchases_date'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['establishment'], name='idx_purchases_establishment'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'purchase_date'], name='idx_purchases_user_date'),
        ),
    ]
