# Generated by Django 4.2.25 on 2025-10-13 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('establishments', '0002_alter_establishment_options_and_more'),
        ('products', '0002_alter_product_options_alter_productcategory_options_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date', '-purchase_time'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['purchase', 'id'], 'verbose_name': 'Item de Compra', 'verbose_name_plural': 'Items de Compra'},
        ),
        migrations.AlterModelOptions(
            name='purchasespendingcategory',
            options={'ordering': ['purchase', 'category'], 'verbose_name': 'Categoría de Compra', 'verbose_name_plural': 'Categorías de Compras'},
        ),
        migrations.AlterModelOptions(
            name='spendingcategory',
            options={'ordering': ['user', 'name'], 'verbose_name': 'Categoría de Gasto', 'verbose_name_plural': 'Categorías de Gasto'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bcv_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Tasa BCV'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='binance_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Tasa Binance'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='card_last_digits',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 Dígitos'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cashier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cajero'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount_ves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Descuento (VES)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='document_type',
            field=models.CharField(max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='establishment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='establishments.establishment', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia de Pago'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Compra'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='raw_json',
            field=models.JSONField(blank=True, null=True, verbose_name='JSON Original'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='register_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Caja'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='spending_categories',
            field=models.ManyToManyField(related_name='purchases', through='purchases.PurchaseSpendingCategory', to='purchases.spendingcategory', verbose_name='Categorías de Gasto'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='subtotal_ves',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal (VES)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Base Imponible'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje de Impuesto'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Impuesto'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax_ves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Impuesto (VES)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tip_ves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Propina (VES)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_usd_bcv',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Total USD (BCV)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_usd_binance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Total USD (Binance)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_ves',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total (VES)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='discount_ves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Descuento (VES)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price_per_unit_usd_bcv',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio/Unidad Std USD (BCV)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price_per_unit_usd_binance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio/Unidad Std USD (Binance)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price_per_unit_ves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio/Unidad Std (VES)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Producto'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='subtotal_usd_bcv',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Subtotal USD (BCV)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='subtotal_usd_binance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Subtotal USD (Binance)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='subtotal_ves',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal (VES)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='tax_ves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Impuesto (VES)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price_usd_bcv',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio Unit. USD (BCV)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price_usd_binance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Precio Unit. USD (Binance)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price_ves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Precio Unitario (VES)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Unidad'),
        ),
        migrations.AlterField(
            model_name='purchasespendingcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.spendingcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='purchasespendingcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='purchasespendingcategory',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color (Hex)'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='purchases.spendingcategory', verbose_name='Categoría Padre'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='spendingcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_categories', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
