# Generated by Django 4.2.25 on 2025-10-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_options_alter_purchaseitem_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spendingcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='spendingcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='spendingcategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='spending_categories',
        ),
        migrations.DeleteModel(
            name='PurchaseSpendingCategory',
        ),
        migrations.DeleteModel(
            name='SpendingCategory',
        ),
    ]
