# Generated by Django 4.2.25 on 2025-11-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_spendingcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='discount_ves',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='subtotal_usd_bcv',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='subtotal_usd_binance',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='subtotal_ves',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='tax_ves',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_usd_bcv',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Total USD (BCV)'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_usd_binance',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Total USD (Binance)'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='total_ves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total (VES)'),
        ),
    ]
