# Generated by Django 4.2.25 on 2025-11-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_remove_purchaseitem_discount_ves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='unit_price_usd_bcv',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='unit_price_usd_binance',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='unit_price_ves',
        ),
    ]
