# Generated by Django 4.2.25 on 2025-11-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_remove_purchaseitem_unit_price_usd_bcv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='price_per_unit_usd_bcv',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='price_per_unit_usd_binance',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='price_per_unit_ves',
        ),
    ]
