# Generated by Django 4.2.25 on 2025-11-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_remove_purchaseitem_price_per_unit_usd_bcv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='card_last_digits',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='discount_ves',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tax_base',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='tip_ves',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='vendor',
        ),
    ]
