# Generated by Django 4.2.25 on 2025-11-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_remove_purchase_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='document_number',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='register_number',
        ),
    ]
