# Generated by Django 4.2.26 on 2025-12-07 14:50

from django.db import migrations, models
import purchases.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_remove_purchase_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to=purchases.models.Purchase.invoice_image_path, verbose_name='Imagen de Factura'),
        ),
    ]
