# Generated by Django 4.2.26 on 2025-11-12 00:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('BCV', 'Banco Central de Venezuela'), ('BINANCE_BUY', 'Binance (Compra P2P)'), ('BINANCE_SELL', 'Binance (Venta P2P)')], help_text='Origen de la tasa de cambio', max_length=20, verbose_name='Fuente')),
                ('rate', models.DecimalField(decimal_places=4, help_text='VES por 1 USD (ej: 36.5000 significa 36.50 Bs por dólar)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Tasa')),
                ('date', models.DateField(db_index=True, help_text='Fecha de vigencia de la tasa', verbose_name='Fecha')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='Momento en que se registró esta tasa en el sistema', verbose_name='Fecha de Registro')),
                ('notes', models.TextField(blank=True, help_text='Información adicional sobre esta tasa (opcional)', null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
                'db_table': 'exchange_rates',
                'ordering': ['-date', 'source'],
                'indexes': [models.Index(fields=['source', 'date'], name='idx_source_date'), models.Index(fields=['-date'], name='idx_date_desc'), models.Index(fields=['source', '-date'], name='idx_source_date_desc')],
                'unique_together': {('source', 'date')},
            },
        ),
    ]
