# Generated by Django 4.2.26 on 2025-11-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-timestamp', '-date', 'source'], 'verbose_name': 'Tasa de Cambio', 'verbose_name_plural': 'Tasas de Cambio'},
        ),
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='idx_source_date_desc',
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Fecha y hora exacta del snapshot (para tasas con intervalo horario)', null=True, verbose_name='Timestamp'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('source', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['source', 'timestamp'], name='idx_source_timestamp'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['-timestamp'], name='idx_timestamp_desc'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['source', '-timestamp'], name='idx_source_ts_desc'),
        ),
    ]
