# Generated by Django 4.2.26 on 2025-11-26 00:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rates', '0002_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_band', models.CharField(choices=[('MIN', 'Mínimo (< AVG)'), ('AVG', 'Promedio (AVG - P75)'), ('P75', 'Percentil 75 (P75 - MAX)'), ('MAX', 'Máximo (>= MAX)')], help_text='Clasificación del spread actual según las bandas históricas', max_length=10, verbose_name='Banda Actual')),
                ('last_check', models.DateTimeField(help_text='Timestamp de la última verificación de spread (cada 15 min)', verbose_name='Última Verificación')),
                ('last_alert_sent', models.DateTimeField(blank=True, help_text='Timestamp de la última alerta enviada a Telegram', null=True, verbose_name='Última Alerta Enviada')),
                ('bands_calculation_date', models.DateField(help_text='Fecha en que se calcularon las bandas históricas', verbose_name='Fecha de Cálculo de Bandas')),
                ('band_min_value', models.DecimalField(decimal_places=2, help_text='Percentil 0 del spread histórico (%)', max_digits=6, verbose_name='Valor Banda MIN')),
                ('band_avg_value', models.DecimalField(decimal_places=2, help_text='Percentil 50 (mediana) del spread histórico (%)', max_digits=6, verbose_name='Valor Banda AVG')),
                ('band_p75_value', models.DecimalField(decimal_places=2, help_text='Percentil 75 del spread histórico (%)', max_digits=6, verbose_name='Valor Banda P75')),
                ('band_max_value', models.DecimalField(decimal_places=2, help_text='Percentil 100 (máximo) del spread histórico (%)', max_digits=6, verbose_name='Valor Banda MAX')),
            ],
            options={
                'verbose_name': 'Estado de Alertas',
                'verbose_name_plural': 'Estado de Alertas',
                'db_table': 'alert_state',
            },
        ),
    ]
