# Generated by Django 4.2.25 on 2025-11-01 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeminiConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_user', models.CharField(blank=True, help_text='Username de Telegram del usuario (sin @)', max_length=100, null=True, unique=True, verbose_name='Usuario de Telegram')),
                ('gemini_psid', models.TextField(help_text='Cookie __Secure-1PSID de gemini.google.com', verbose_name='__Secure-1PSID')),
                ('gemini_psidts', models.TextField(help_text='Cookie __Secure-1PSIDTS de gemini.google.com', verbose_name='__Secure-1PSIDTS')),
                ('gemini_papisid', models.TextField(blank=True, help_text='Cookie __Secure-1PAPISID de gemini.google.com (opcional)', null=True, verbose_name='__Secure-1PAPISID')),
                ('proxy', models.CharField(blank=True, help_text='URL del proxy (opcional). Ejemplo: http://proxy.ejemplo.com:8080', max_length=255, null=True, verbose_name='Proxy')),
                ('is_active', models.BooleanField(default=True, help_text='Si está desactivado, no se podrá usar OCR con este usuario', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('last_used', models.DateTimeField(blank=True, help_text='Última vez que se usó OCR con estas credenciales', null=True, verbose_name='Último Uso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gemini_config', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Gemini',
                'verbose_name_plural': 'Configuraciones de Gemini',
                'db_table': 'user_gemini_configs',
                'ordering': ['user__username'],
            },
        ),
    ]
