# Generated by Django 4.2.25 on 2025-11-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergeminiconfig',
            name='preferred_model',
            field=models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash (Rápido y eficiente) ⚡'), ('gemini-2.5-pro', 'Gemini 2.5 Pro (Más potente, límite diario) 🧠'), ('gemini-2.0-flash', 'Gemini 2.0 Flash (Versión anterior)'), ('gemini-2.0-flash-thinking', 'Gemini 2.0 Flash Thinking (Con razonamiento)'), ('unspecified', 'Sin especificar (Usa modelo por defecto de Gemini)')], default='gemini-2.5-flash', help_text='Modelo de Gemini que se usará por defecto para este usuario', max_length=50, verbose_name='Modelo Preferido'),
        ),
    ]
