# Generated by Django 4.2.25 on 2025-11-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_usergeminiconfig_preferred_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergeminiconfig',
            name='gemini_psid',
            field=models.TextField(blank=True, help_text='Cookie __Secure-1PSID de gemini.google.com', null=True, verbose_name='__Secure-1PSID'),
        ),
        migrations.AlterField(
            model_name='usergeminiconfig',
            name='gemini_psidts',
            field=models.TextField(blank=True, help_text='Cookie __Secure-1PSIDTS de gemini.google.com', null=True, verbose_name='__Secure-1PSIDTS'),
        ),
    ]
