# Generated by Django 4.2.25 on 2025-11-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('normalized_name', 'brand')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_type',
        ),
    ]
