# Generated by Django 4.2.25 on 2025-11-03 12:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Marca de Producto',
                'verbose_name_plural': 'Marcas de Productos',
                'db_table': 'product_brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, verbose_name='Tipo')),
                ('value', models.CharField(max_length=100, verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'db_table': 'product_variants',
                'ordering': ['type', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Asignación de Variante',
                'verbose_name_plural': 'Asignaciones de Variantes',
                'db_table': 'product_variant_assignments',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'brand'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='idx_products_normalized_name',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Normalizado'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_products_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='idx_products_brand'),
        ),
        migrations.AddField(
            model_name='productvariantassignment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_assignments', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='productvariantassignment',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_assignments', to='products.productvariant', verbose_name='Variante'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['type', 'value'], name='idx_variants_type_value'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('type', 'value')},
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.ManyToManyField(related_name='products', through='products.ProductVariantAssignment', to='products.productvariant', verbose_name='Variantes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productbrand', verbose_name='Marca'),
        ),
        migrations.AddIndex(
            model_name='productvariantassignment',
            index=models.Index(fields=['product'], name='idx_var_assign_product'),
        ),
        migrations.AddIndex(
            model_name='productvariantassignment',
            index=models.Index(fields=['variant'], name='idx_var_assign_variant'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariantassignment',
            unique_together={('product', 'variant')},
        ),
    ]
