# Generated by Django 4.2.25 on 2025-11-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productbrand_productvariant_productvariantassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='normalized_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
